<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'Irw',
  'author' => 'Daniel Martinez Osorio',
  'description' => 'Analiza la información del sistema creando las inconformidades pertinentes.',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'instructions',
  'published_date' => '2020-02-11 17:05:29',
  'type' => 'module',
  'version' => 1581440730,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'instructions',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Irw_data_audits',
      'class' => 'Irw_data_audits',
      'path' => 'modules/Irw_data_audits/Irw_data_audits.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'Irw_management_reports',
      'class' => 'Irw_management_reports',
      'path' => 'modules/Irw_management_reports/Irw_management_reports.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'Irw_myreviews',
      'class' => 'Irw_myreviews',
      'path' => 'modules/Irw_myreviews/Irw_myreviews.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'Irw_input_reports',
      'class' => 'Irw_input_reports',
      'path' => 'modules/Irw_input_reports/Irw_input_reports.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'Irw_indicators',
      'class' => 'Irw_indicators',
      'path' => 'modules/Irw_indicators/Irw_indicators.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'Irw_audits',
      'class' => 'Irw_audits',
      'path' => 'modules/Irw_audits/Irw_audits.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'Irw_procesos',
      'class' => 'Irw_procesos',
      'path' => 'modules/Irw_procesos/Irw_procesos.php',
      'tab' => true,
    ),
    7 => 
    array (
      'module' => 'Irw_indicator_datas',
      'class' => 'Irw_indicator_datas',
      'path' => 'modules/Irw_indicator_datas/Irw_indicator_datas.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/irw_myreviews_activities_calls_Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/irw_myreviews_activities_callsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/irw_myreviews_activities_meetingsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/irw_myreviews_activities_notesMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/irw_myreviews_activities_tasksMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/irw_myreviews_activities_emailsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_data_audits',
      'to' => 'modules/Irw_data_audits',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_management_reports',
      'to' => 'modules/Irw_management_reports',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_myreviews',
      'to' => 'modules/Irw_myreviews',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_input_reports',
      'to' => 'modules/Irw_input_reports',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_indicators',
      'to' => 'modules/Irw_indicators',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_audits',
      'to' => 'modules/Irw_audits',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_procesos',
      'to' => 'modules/Irw_procesos',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Irw_indicator_datas',
      'to' => 'modules/Irw_indicator_datas',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'es_ES',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
      'language' => 'es_ES',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_calls_Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_meetings_Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_notes_Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_tasks_Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/irw_myreviews_activities_emails_Irw_myreviews.php',
      'to_module' => 'Irw_myreviews',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'irw_myreviews_activities_calls_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'irw_myreviews_activities_meetings_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'irw_myreviews_activities_notes_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'irw_myreviews_activities_tasks_name',
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);